name: Python CI Pipeline with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
         python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files in tests directory
      run: |
        ls -R tests/

    - name: Run tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q # This will run all tests in the 'tests' directory

  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Build code
      run: |
        pip install -r requirements.txt

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
