name: Python CI Pipeline with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ # Adjust this path if your tests are located elsewhere
        # Or replace with your project's test command (e.g., `pytest` if you want it to check the whole repo)

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Build code
      run: |
        pip install -r requirements.txt

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
